spring:
  config:
    import: "configserver:http://config-service:8083"
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
